### ISSUE TITLE
Printing Image

### ISSUE THREAD

**Issue by abdkaviani** [ianthrive/datamax#1]
Hello Ian

This is a simple datamax code to printing my image:

$command = "\x02qA\x0d";
$command .= "\x02IAAFLOGO\x0d";
$command .= "801100000000FFFFFFFFFFFFFFFFFFFFFFFF00\x0d";
$command .= "801100000000FFFFFFFFFFFFFFFFFFFFFFFF00\x0d";
$command .= "801100000000FFFFFFFFFFFFFFFFFFFFFFFF00\x0d";
$command .= "801100000000FFFFFFFFFFFFFFFFFFFFFFFF00\x0d";
$command .= "801100000000FFFFFFFFFFFFFFFFFFFFFFFF00\x0d";
$command .= "801100000000FFFFFFFFFFFFFFFFFFFFFFFF00\x0d";
$command .= "801100000000FFFFFFFFFFFFFFFFFFFFFFFF00\x0d";
$command .= "FFFF\x0d";
$command .= "\x02L\x0d";
$command .= "1Y1100000000000LOGO\x0d";
$command .= "E\x0d";

I found a solution to convert my image to datamax format (edit [this sample](https://github.com/pbosakov/image2zpl/blob/master/image2zpl.inc.php)), but my result is not suitable or bad resolution. Do you know best function to printing an image with Datamax language with php?

**Comment by ianthrive** [comment]
I don't have a direct answer for your question. However, a couple thoughts:

Check out page 20 and 139 of the PDF manual in this repository.

The solution to which you link is for ZPL (Zebra Printing Language). As a general rule, ZPL is not compatible with older Datamax printers. I don't know if your snippet is Datamax-compatiable.

**Comment by abdkaviani** [comment]
Thanks

I edited above link according to the Datamax manual
This is my function and it works for me in most cases
I hope somebody to write perfect function :)

function imageToDPL($in, $name='') {
	$res = "";
	if(empty($in)) return '';
	$im = imagecreatefrompng($in);
	if ($im === false) return false;
	// Black and white only
	imagefilter($im, IMG_FILTER_GRAYSCALE); //first, convert to grayscale
	imagefilter($im, IMG_FILTER_CONTRAST, -255); //then, apply a full contrast
	// Convert to WBMP
	ob_start();
	imagewbmp($im);
	$wbmp = ob_get_contents();
	ob_end_clean();
	$type = uintvar_shift($wbmp);
	$fixed = uintvar_shift($wbmp);
	$w = uintvar_shift($wbmp);
	$h = uintvar_shift($wbmp);
	$bitmap = str_split(~$wbmp); // Black is white, white is black
	$total_bytes = count($bitmap);
	$bytes_per_line = ceil($w/8);
	if($w % 8 > 0) {
		// End of line is padded with black; make that white
		// Get last byte of each line
		$period = ceil($w/8);
		for($i=$bytes_per_line; $i <= $total_bytes; $i+=$bytes_per_line) {
			$byte = ord($bitmap[$i-1]);
			for($j=1; $j<=$w%8; $j++) {
				// Flip j-th bit
				$byte = $byte & (~(1<<($j-1)));
			}
			$bitmap[$i-1] = chr($byte);
		}
	}
	$bitmap = implode("", $bitmap);
	$uncompressed = strtoupper(bin2hex($bitmap));
	$prtLine = strtoupper(dechex($bytes_per_line));
	//echo "width:".$w." height:".$h." total:".$total_bytes." per_line:".$bytes_per_line." length:".strlen($uncompressed)."<br>";
	for($k=strlen($uncompressed);$k>=0;$k-=($bytes_per_line*2))
	$res .= "80".$prtLine.substr($uncompressed,$k,($bytes_per_line*2))."\x0d";
	//$r = $uncompressed;
	return $res;
}
function uintvar_shift(&$data) {
	$index = 0;
	$r = 0;
	while ((ord($data[$index]) & 0x80) != 0) {
		if ($index >= 4) {
		    return false;
		}
		$r = ($r << 7) | (ord($data[$index]) & 0x7f);
		$index++;
	}
	$r = ($r << 7) | (ord($data[$index]) & 0x7f);
	$data = substr($data, $index + 1);
	return $r;
}
